sudo: required

language: python
python:
  - "3.6"

services:
  - mongodb

addons:
  apt:
    packages:
    - firefox
    - time
    - unzip

before_install:
  - >
    wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz &&
    tar -xvzf geckodriver* &&
    chmod +x geckodriver &&
    sudo mv geckodriver /usr/local/bin/
    
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/ubuntu wheezy/snapshots/4.8.1 main"
    | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install -y clang
  - sudo apt-get install -y mono-complete
  - sudo wget https://github.com/inkle/ink/releases/download/0.7.4/inklecate_windows_and_linux.zip
  - cd $TRAVIS_BUILD_DIR
  - unzip inklecate_windows_and_linux.zip
  - chmod +x inklecate.exe

install:
  - pip install -U setuptools
  - pip install pycparser
  - pip install codecov
  - pip install pytest pytest-cov pytest-asyncio
  - pip install -e .
  - pip install -r requirements.txt

script:
  - python -m pytest --cov=./

after_success:
  - codecov